### ISSUE TITLE
Possible improvements to operator tutorial

### ISSUE THREAD

**Issue by siyer-123** [deepak1725/hello-operator2#1]
Hi Deepak, my work colleagues and I saw your tutorial to [build a "Hello World" operator ](https://developers.redhat.com/articles/2021/09/07/build-kubernetes-operator-six-steps#). Thanks for writing this tutorial out. It helped us understand our work a little bit more from a foundational perspective. 

As we were going through the tutorial, we noticed a few things that might be useful to update in the instructions. Below is the list:

1. When we tried using the latest version of go available (`1.17`), I ran into a few errors that prevented the tutorial from moving forward. Go version `1.15` also did not work. I see when you wrote your directions, the go version you used was `go1.16`, which ended up working as expected. It might be helpful for future learners to point out that `1.16` is the only supported version for the tutorial to avoid confusion.
2. We initially found [the older tutorial](https://developers.redhat.com/blog/2020/08/21/hello-world-tutorial-with-kubernetes-operators#) and were going to follow that until we discovered the newer one under your profile. It would be helpful to point out the new tutorial at the start of the old one in case someone wants to use the latest information.
3. The latest tutorial is in the context of `minikube`. It would be helpful if a tutorial could be made in the context of `OpenShift` as well. For example, in the original tutorial, we're able to access the webpage using `minikube service backend-service`. With `OpenShift`, we weren't able to access the web server page through a cluster environment. It would be great to include additional instruction on how to access it from outside the cluster if possible.

**Comment by deepak1725** [comment]
Hi @siyer-123 

Thank you for your patience.

As per request, 
1. Golang version fixed. [Build Operator Pre-requisites](https://developers.redhat.com/articles/2021/09/07/build-kubernetes-operator-six-steps#setup_and_prerequisites) 
Thanks for notifying me.
 
2. The Old Article: [Hello World with K8s Operator](https://developers.redhat.com/blog/2020/08/21/hello-world-tutorial-with-kubernetes-operators)  has been updated with a Notice. 
![image](https://user-images.githubusercontent.com/21026016/150296339-f9addff0-3332-4fb1-849c-5aae3caa3101.png)

3. Actually most of the readers are already familiar with Kubernetes, I believe once they have already experienced building the Operator in Kubernetes, they could easily make it Openshift compatible. :). Also As of now, vanilla K8s is more Local environment friendly.
